### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by neko-kage** [pluto0x0/ncmd#1]
点击登录按钮之后会变灰

**Comment by pluto0x0** [comment]
是原先的api地址失效了。可以将`config.json`里`baseURL`项的值改成`https://netease-cloudmusic-api.vercel.app`

在[Version0.9](https://github.com/pluto0x0/ncmd/releases/tag/0.9)里已经修改了默认的api地址，可以直接下载使用。

另外，Version0.9修复了导致崩溃的时间戳bug，**强烈建议使用该版本。**
